

## kube-proxy

- name: 准备kube-proxy 证书签名请求
  template:
    src: templates/kube-proxy-csr.json.j2
    dest: "{{install_path}}/ssl/kube-proxy-csr.json"

- name: 创建 kube-proxy证书与私钥
  shell: "cd {{install_path}}/ssl && {{install_path}}/{{modules.cfssl}}/cfssl gencert \
        -ca={{install_path}}/ssl/ca.pem \
        -ca-key={{install_path}}/ssl/ca-key.pem \
        -config={{install_path}}/ssl/ca-config.json \
        -profile=kubernetes kube-proxy-csr.json | {{install_path}}/{{modules.cfssl}}/cfssljson -bare kube-proxy"

#创建kube-proxy.kubeconfig配置文件
- name: 设置集群参数
  shell: "kubectl config set-cluster kubernetes \
        --certificate-authority={{install_path}}/ssl/ca.pem \
        --embed-certs=true \
        --server=https://{{vip}}:6443 \
        --kubeconfig={{install_path}}/kubeconfig/kube-proxy.kubeconfig"
- name: 设置客户端认证参数
  shell: "kubectl config set-credentials kube-proxy \
        --client-certificate={{install_path}}/ssl/kube-proxy.pem \
        --client-key={{install_path}}/ssl/kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig={{install_path}}/kubeconfig/kube-proxy.kubeconfig"
- name: 设置上下文参数
  shell: "kubectl config set-context default \
        --cluster=kubernetes \
        --user=kube-proxy \
        --kubeconfig={{install_path}}/kubeconfig/kube-proxy.kubeconfig"
- name: 选择默认上下文
  shell: "kubectl config use-context default --kubeconfig={{install_path}}/kubeconfig/kube-proxy.kubeconfig"



