---
- name: set local_hostname 
  vars_files:
    - default.yml
  hosts: local
  tasks: 
  - name: defined local_hostname
    set_fact:
      local_hostname: "{{inventory_hostname}}"
    run_once: true
  tags:
    - master 

- name: init all nodes
  hosts: kube-cluster
  vars_files:
    - default.yml
  roles:
    - init
    - pkg2nodes
    - docker 
#    - images
    - ca 
    - kubectl
    - kubelet
  tags:
    - master 

- name: init master nodes 
  hosts: master
  vars_files:
    - default.yml
  roles:
    - etcd
    - keepalived
  tags:
    - master 
  

- name: install master nodes
  hosts: master
  vars_files:
    - default.yml
  roles:
    - kube-master
    - kube-addons  
    - harbor
  tags:
    - master 
    - harbor

- name:  install nodes
  hosts: nodes
  vars_files:
    - default.yml
  roles:
    - kube-nodes
  tags:
    - nodes

- name: marker nodes 
  vars_files:
    - default.yml
  hosts: local
  tasks: 
  - name:  marker nodes and enable schedule
    shell: " kubectl label  nodes {{item.name}}  node-role.kubernetes.io/nodes=true --overwrite ; \
             kubectl taint nodes  {{item.name}}  node-role.kubernetes.io/master- --overwrite || echo ok "
    with_items: "{{nodes}}"
    run_once: true
  tags:
    - nodes


