
- name: uninstall all nodes
  hosts: all
  vars_files:
    - default.yml
  tasks:
  - name: stop  services
    service: 
      name: "{{item}}"
      enabled: no
      state:  stopped
    with_items:
    - docker
    - kubelet
    - keepalived 
    ignore_errors: true
  
  - name: remove old  data
    file:
      path: "{{item}}"
      state: absent
    with_items:
    - /etc/default/docker
    - /usr/local/bin/docker
    - /var/lib/etcd
    - "{{install_path}}/"
    - /run/flannel/subnet.env
    - /usr/lib/systemd/system/docker.service
    - /usr/lib/systemd/system/docker.socket
    - /usr/lib/systemd/system/etcd.service
    - /usr/lib/systemd/system/keepalived.service
    - /usr/lib/systemd/system/kubelet.service
    ignore_errors: true
  
  - name: remove  flannel cni bridge  
    shell: "(ip link del dev cni0 ; ip link del dev  flannel.1 ) || echo ok"
    ignore_errors: true 
  
