---
#- name: mkdir install directory
#  file:
#    path: "{{install_path}}"
#    state: directory
#
- name: distribute service binary packages to all nodes 
  unarchive:
    src: "files/{{item.value}}.tar.gz"
    dest: "{{install_path}}"
  with_dict: "{{modules}}"
#  when: item.key=="kube" or item.key=="docker" or item.key=="docker_registry" 

