apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --data-dir=/var/lib/etcd
    image: {{registry.domain}}/etcd-arm64:3.0.17
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    env:
{% for host in master %}
{% if ansible_default_ipv4.address  == host.ip %}
      - name: ETCD_NAME
        value: kylincloud2{{loop.index}}
{% endif %}
{% endfor %}
      - name: ETCD_LISTEN_PEER_URLS
        value: http://{{ansible_default_ipv4.address}}:2380
      - name: ETCD_LISTEN_CLIENT_URLS
        value: http://{{ansible_default_ipv4.address}}:2379,http://127.0.0.1:2379
      - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
        value: http://{{ansible_default_ipv4.address}}:2380
      - name: ETCD_INITIAL_CLUSTER
        value: {% for host in master -%}
                 kylincloud2{{loop.index}}=http://{{host.ip}}:2380
                 {%- if not loop.last -%}
                   ,
                 {%- endif -%}
               {%- endfor %} 
      - name: ETCD_INITIAL_CLUSTER_STATE
        value: new
      - name: ETCD_INITIAL_CLUSTER_TOKEN
        value: k8s-etcd-cluster
      - name: ETCD_ADVERTISE_CLIENT_URLS
        value: http://{{ansible_default_ipv4.address}}:2379
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd
status: {}
