---
- name: execute daemon-reload
  shell: systemctl daemon-reload

- name: restart docker.socket
  service: name=docker.socket enabled=yes state=restarted

- name: restart docker
  service: name=docker enabled=yes state=restarted

