apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-clair-config
  namespace: registry
data:
  POSTGRES_PASSWORD: {{registry.clair_password}}
  clair-config: |
    clair:
      database:
        type: pgsql
        options:
          source: postgresql://postgres:{{registry.clair_password}}@postgres:5432?sslmode=disable
    
          # Number of elements kept in the cache
          # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
          cachesize: 16384
    
      api:
        # API server port
        port: 6060
        healthport: 6061
    
        # Deadline before an API request will respond with a 503
        timeout: 300s
      updater:
        interval: 0
    
      notifier:
        attempts: 3
        renotifyinterval: 2h
        http:
          endpoint: http://ui/service/notifications/clair

