---
#- name: mkdir install directory
#  file:
#    path: "{{install_path}}"
#    state: directory
#
#- name: load images in local nodes 
#  shell: "docker load -i /{{item}}"
#  with_fileglob:
#    -  "files/*"

