apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobservice-rc
  labels:
    name: jobservice-rc
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jobservice-apps
  template:
    metadata:
      labels:
        name: jobservice-apps
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
        node-role.kubernetes.io/master: 'true'
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: jobservice-app
        image: kylincloud2.hub/harbor-jobservice:1.2.2
        imagePullPolicy: IfNotPresent
        env:
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: JOBSERVICE_SECRET
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: LOG_LEVEL
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: GODEBUG
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: harbor-jobservice-config
          items:
          - key: config
            path: app.conf
      - name: logs
        persistentVolumeClaim:
          claimName: log-pvc 

---
apiVersion: v1
kind: Service
metadata:
  name: jobservice
  namespace: registry
spec:
  ports:
    - port: 80
  selector:
    name: jobservice-apps
