apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui-rc
  labels:
    name: ui-rc
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ui-apps
  template:
    metadata:
      labels:
        name: ui-apps
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
        node-role.kubernetes.io/master: 'true'
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: ui-app
        image: kylincloud2.hub/harbor-ui:1.2.2
        imagePullPolicy: IfNotPresent
        env:
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: CONFIG_PATH
          - name: NOTARY_SERVER_URL
            valueFrom:
              configMapKeyRef:
               name: harbor-ui-config
               key: NOTARY_SERVER_URL
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: LOG_LEVEL
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: JOBSERVICE_SECRET
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: GODEBUG
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/ui
      volumes:
      - name: config
        configMap:
          name: harbor-ui-config
          items:
          - key: config
            path: app.conf
          - key: pkey
            path: private_key.pem
          - key: SECRET_KEY
            path: key

---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: registry
spec:
  ports:
    - port: 80
  selector:
    name: ui-apps
