---
- name: remove default docker
  shell: "dpkg -P docker.io"

- name: remove docker.service
  file:
    path: /etc/systemd/system/docker.service
    state: absent

- name: link docker add PATH
  file:
    src: "{{install_path}}/{{modules.docker}}/docker"
    dest: /usr/local/bin/docker
    state: link 
  ignore_errors: true

- name: configure docker.socket systemd
  copy:
    src: files/docker.socket
    dest: /usr/lib/systemd/system/
  notify:
    - execute daemon-reload
    - restart docker

- name: configure service docker's systemd
  template:
    src: templates/docker.service
    dest: /usr/lib/systemd/system/
  notify:
    - execute daemon-reload
    - restart docker

- name: configure service docker's options
  template:
    src: templates/docker
    dest: /etc/default
  notify:
    - execute daemon-reload
    - restart docker
#    - execute add  registry  SSL cert

- name: make sure the docker is running 
  shell: "systemctl restart docker"

