apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --address=127.0.0.1 
    - --master=http://127.0.0.1:8080 
    - --allocate-node-cidrs=true 
    - --service-cluster-ip-range={{service.cidr}} 
    - --cluster-cidr={{pod_net.cidr}} 
    - --cluster-name=kubernetes 
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.pem 
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca-key.pem 
    - --service-account-private-key-file=/etc/kubernetes/pki/ca-key.pem 
    - --root-ca-file=/etc/kubernetes/pki/ca.pem 
    - --leader-elect=true 
    - --v=2
    image: kylincloud2.hub/kube-controller-manager-arm64:v1.8.3
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/pki
      name: ca-certs-etc-pki
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: {{install_path}}/ssl
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: ca-certs-etc-pki
status: {}
